services:
  gwynethllewelyn.postlocalstorage.listener:
    class: gwynethllewelyn\postlocalstorage\event\listener
    arguments:
      - '@template'
      - '@user'
      - '@request'
      - '@config'
    tags:
        - { name: event.listener }